server:
  port: 8080

spring:
  datasource:
    username:
    password:
    url:
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mybatis/*Mapper.xml
  type-aliases-package: com.rsbdcsn.myblog.bean
