server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://192.168.253.201:3306/myblog
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mybatis/*Mapper.xml
  type-aliases-package: com.rsbdcsn.myblog.bean
